### ISSUE TITLE
Cannot compile with CUDA 7.5

### ISSUE THREAD

**Issue by bedbc** [mimblewimble/grin-miner#13]
CPU miner compiles fine, but fails after enabling:
`features=["build-cuda-plugins"]
`
Compiling with nvcc V7.5.17

Sample errors:
`/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined
~/.cargo/git/checkouts/cuckoo-miner-4752934f0f1f2bfe/2a08251/src/cuckoo_sys/plugins/cuckoo/src/mean_miner.cu(361): error: Within a __device__/__global__ function, only __shared__ variables may be marked "static"
`

**Comment by emmick4** [comment]
Also having issues building with CUDA 7.5

**Comment by yeastplume** [comment]
Cuda 7.5 is very old at this stage, is it the default on some distro?

I need to create proper documentation for this package, but it's only ever targeted Cuda 9+. Could you try upgrading and try again?

**Comment by kngako** [comment]
Hi @bedbc and @emmick4, I had a related C or CXX related issues. You would have the same error by using either gcc-5 or gcc-6. I solved most of these issues by upgrading from gcc-6 to gcc-7.  Give it a try and let me know if it solves your problem.

Had to do a lot of "update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 <priority-level>"  to make sure all C and CXX compilers are set to gcc-7. Things like c++, cc, and the likes weren't what they were supposed to be for reasons I can't recall on my machine.
